### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by langston-barrett** [idanarye/rust-typed-builder#100]
Looks like support for syn 2 was added in https://github.com/idanarye/rust-typed-builder/commit/1626e3e26951af04cd1d78d316dce62d6d98f849 / #85, but that change is not yet in [the latest release on crates.io](https://crates.io/crates/typed-builder/0.14.0/dependencies). This crate is a transitive dependency of my project, and I'd like to upgrade all of my transitive dependencies to use syn 2 so I can avoid compiling both syn 1 and syn 2 (syn takes a long time to compile). Any chance you could push a new release to crates.io? Much appreciated!

**Comment by idanarye** [comment]
Right, sorry about that. I wanted to to make a release after #95 and #96 get merged, but I guess there is no reason not to do one now and another once they are in.

Also, congrats on issue number 100!

**Comment by mo8it** [comment]
I don't think that we have to wait. I am very busy right now so my PR will delay. You can just make a release :D
