### ISSUE TITLE
Add `#[automatically_derived]` to generated code

### ISSUE THREAD

**Issue by xFrednet** [idanarye/rust-typed-builder#114]
The `#[automatically_derived]` attribute is used to indicate that the code was generated by a derive macro and should not be checked by linters. See [stackoverflow](https://stackoverflow.com/questions/51481551/what-does-automatically-derived-mean)

Adding the attribute might also fix:
* https://github.com/idanarye/rust-typed-builder/issues/112
* https://github.com/idanarye/rust-typed-builder/issues/113

automatically

**Comment by idanarye** [comment]
It doesn't fix them (I checked), but I'll add it anyway.
