### ISSUE TITLE
Update syn, quote & proc-macro2 dependencies

### ISSUE THREAD

**Issue by mwilliammyers** [idanarye/rust-typed-builder#25]
Now that #16 is merged, we should probably update the `syn`, `quote` and `proc-macro2` dependencies as they have all reached 1.0.0.

I will probably have time to tackle this...

**Comment by idanarye** [comment]
Reading the list of breaking changes at https://github.com/dtolnay/syn/releases/tag/1.0.0, I think that the only relevant change is the `tts` -> `tokens` rename.
