### ISSUE TITLE
setter through Into-types does not seem to work

### ISSUE THREAD

**Issue by mismosmi** [idanarye/rust-typed-builder#33]
Hi,
Sorry if I'm just a bit confused whether this is intended:

I'm trying to use setters with string literals for string-type fields
```rust
#[derive(TypedBuilder)]
struct MyStruct {
  text: String
}
MyStruct::builder().text("abc").build()
```
and get a mismatched type errors. If I understand the readme correctly this should work, right?

**Comment by mismosmi** [comment]
I'm still a bit of a beginner but I guess I could write and send you a fix for this myself if you don't have time for it, just asking if it's intended.

**Comment by idanarye** [comment]
Yes, this is intended - the readme is out of date. It was [a breaking change in version 0.5.0](https://github.com/idanarye/rust-typed-builder/blob/master/CHANGELOG.md#changed).

This should work:
```rust
#[derive(TypedBuilder)]
struct MyStruct {
  #[builder(setter(into))]
  text: String
}
MyStruct::builder().text("abc").build()
```

**Comment by mismosmi** [comment]
Ah great, thanks!
