### ISSUE TITLE
Ability to skip default values for private types?

### ISSUE THREAD

**Issue by bbqsrc** [idanarye/rust-typed-builder#36]
Say I have a struct:

```rust
struct Foo {
    #[builder(default)]
    secret_constant: SomePrivateType,
    pub some_field: Field
}
```

This field is private, and its type is private. Right now I'll get the error `can't leak private type`.

Is it possible to work around this?

**Comment by idanarye** [comment]
You can skip the setter:

```rust
#[derive(typed_builder::TypedBuilder)]
pub struct Foo {
    #[builder(default, setter(skip))]
    secret_constant: SomePrivateType,
    pub some_field: Field
}
```

Sadly the macro can't do it automatically, because it does not know what the visibility of the `SomePrivateType` is.

**Comment by bbqsrc** [comment]
Super, thanks a lot! I didn't find this when I searched for skip.
