### ISSUE TITLE
How to set default value for String field?

### ISSUE THREAD

**Issue by gembin** [idanarye/rust-typed-builder#38]
```rust
const DEFAULT_VALUE: &str = "test";

#[derive(TypedBuilder)]
pub struct Foo {

    #[builder(default=?)]  //  <--- how to set to DEFAULT_VALUE here
    pub bar: String,

}
```

**Comment by idanarye** [comment]
```rust
#[derive(TypedBuilder)]
pub struct Foo {
    #[builder(default=DEFAULT_VALUE.to_owned())]
    pub bar: String,
}
```

Note that this will allocate each time you `.build()` a `Foo`. Because you need to allocate. You can't get a `String` without allocating memory.

**Comment by gembin** [comment]
Yes, I know it will allocate memory each time.  And I tried `#[builder(default=DEFAULT_VALUE.to_owned())]`, but got error
```
error: invalid attribute: expected literal

#[builder(default= DEFAULT_VALUE.to_owned())]
                   ^^^^^^^^^^^^^
```

**Comment by idanarye** [comment]
Are you using an old version of Rust or of typed-builder?

**Comment by idanarye** [comment]
Rust before 1.34 will not allow something like `DEFAULT_VALUE.to_owned()` in an attribute - only literals. Typed builder before 0.5 was using an old `syn` that could only parse literals in attributes.

**Comment by gembin** [comment]
Thanks!  I used `rustc 1.42.0` and `typed-builder = "0.6.0"`. 
It seems caused by crate `derivative = "2.1.1"` (https://github.com/mcarton/rust-derivative),   but I don't know why.

It will fail with **error: invalid attribute: expected literal**   if I use `Derivative` from `derivative = "2.1.1"`

```rust
// FAILED

use typed_builder::TypedBuilder;
use derivative::Derivative;

#[derive(Derivative, TypedBuilder)]
#[derivative(Debug)]
pub struct Foo {
    #[builder(default=DEFAULT_VALUE.to_owned())]
    pub bar: String,

    #[derivative(Debug = "ignore")]
    pub foo: String,
}
```

```rust
// SUCCESS

use typed_builder::TypedBuilder;
// use derivative::Derivative;

#[derive(Debug, TypedBuilder)]
// #[derivative(Debug)]
pub struct Foo {
    #[builder(default=DEFAULT_VALUE.to_owned())]
    pub bar: String,

    //#[derivative(Debug = "ignore")]
    pub foo: String,
}
```

**Comment by idanarye** [comment]
Yes, [it does look like the error comes from there](https://github.com/mcarton/rust-derivative/blob/d9fd22e67a58a3f68028d784adbde91c783a065b/src/attr.rs#L755). Though maybe I am at fault too, for supporting this style.

Maybe I should bring `default_code` back?

**Comment by gembin** [comment]
Yes, I think so,  or any other solutions?

**Comment by idanarye** [comment]
Actually... no. This is 100% Derivative's fault - they try to parse the attribute to `Meta` before checking it's `path`.
