### ISSUE TITLE
a single default that applies for all fields

### ISSUE THREAD

**Issue by petar-dambovaliev** [idanarye/rust-typed-builder#43]
the titles says it all

**Comment by idanarye** [comment]
Do you mean a default **value** for all fields?
```rust
#[derive(TypedBuilder)]
#[builder(default = 13)]
struct Foo {
    a: u32,
    b: u32,
    c: u32,
}

assert!(
    Foo::builder().build(),
    Foo { a: 13, b: 13, c: 13 });
```

Or default **settings** for all fields?

```rust
#[derive(TypedBuilder)]
#[builder(default, setter(strip_option))]
struct Foo {
    a: Option<u32>,
    b: Option<String>,
    c: Option<f32>,
}

assert!(
    Foo::builder().a(1).c(2.3).build(),
    Foo { a: Some(1) b: None c: Some(2.3) });
```
The second option makes more sense - though we'll need to add syntax to turn settings for specific fields off...

**Comment by petar-dambovaliev** [comment]
> Do you mean a default **value** for all fields?
> ```rust
> #[derive(TypedBuilder)]
> #[builder(default = 13)]
> struct Foo {
>     a: u32,
>     b: u32,
>     c: u32,
> }
> 
> assert!(
>     Foo::builder().build(),
>     Foo { a: 13, b: 13, c: 13 });
> ```
> 
> Or default **settings** for all fields?
> 
> ```rust
> #[derive(TypedBuilder)]
> #[builder(default, setter(strip_option))]
> struct Foo {
>     a: Option<u32>,
>     b: Option<String>,
>     c: Option<f32>,
> }
> 
> assert!(
>     Foo::builder().a(1).c(2.3).build(),
>     Foo { a: Some(1) b: None c: Some(2.3) });
> ```
> The second option makes more sense - though we'll need to add syntax to turn settings for specific fields off...

I mean `default` without any arguments, meaning none of the fields would be required. I have certain structs that have like 25 fields and in tests I only care about 5. That leads me to having 20 default attributes to each field I don't care about.

**Comment by idanarye** [comment]
Can you try the `feature/field-defaults` and see if it's suitable for your needs? You can do it by putting this in your `Cargo.toml`:
```toml
typed-builder = { git = "https://github.com/idanarye/rust-typed-builder", branch = "feature/field-defaults" }
```

**Comment by petar-dambovaliev** [comment]
> Can you try the `feature/field-defaults` and see if it's suitable for your needs? You can do it by putting this in your `Cargo.toml`:
> 
> ```toml
> typed-builder = { git = "https://github.com/idanarye/rust-typed-builder", branch = "feature/field-defaults" }
> ```
> 
> This is the syntax:
> 
> ```rust
> #[derive(TypedBuilder)]
> #[builder(field_defaults(default))]
> struct Foo {
>     a: u32,
>     b: String,
>     #[builder(!default)] // make c mandatory
>     c: f32,
> }
> ```

This one works for what i need. Thanks.
