### ISSUE TITLE
feature request: Custom `build` method

### ISSUE THREAD

**Issue by lebensterben** [idanarye/rust-typed-builder#52]
## Status quo

Currently, if we have a struct `Foo` that derive `TypedBuilder`, it will generate something like
```rust
impl Foo {
  pub fn builder() -> FooBuilder<...>;
}
impl FooBuilder {
  pub fn build(self) -> Foo;
}
```

## Inconvenience

But there are some use cases that `Foo` is just an intermediate type, or `Foo` is itself a builder.

With `derive-builder`, it's possible to have, for example
```rust
pub struct Foo { /* fields omitted */ };
pub struct FooBuilder {
  foo: u8,
  bar: u8,
}
```
where `FooBuilder` derive the builder pattern. But user can override the `build()` function, so that
something like
```
FooBuilder::default().foo(1).bar(2).build()?
```
Generates a `Result<Foo, ..>` instead of `Result<FooBuilder, ..>`.

I understand that the mechanism of typed builder is different. And to achieve the same effect, I need to write something like
```rust
impl FooBuilder {
  pub fn build_foo(self) -> Result<Foo, ..>;
}
```
and
```
FooBuilder::builder().foo(1).bar(2).build().build_foo()?
```

## Proposal

I suggest to add a struct level attribute, `builder_into`, for example
```rust
pub struct Foo { /* fields omitted */ };

#[derive(TypedBuilder)]
#[builder(build_into = "Foo")]
pub struct FooBuilder { /* fields omitted */ };

impl From<FooBuilder> for Foo {
  fn from(foo_builder: FooBuilder) -> Foo;
}
```

And if `build_into` is empty, `FooBuilderBuilder::build()` should maintain the current behaviour.
And if it's not, as in the case above, it should behave like
```rust
<FooBuilder as Into<Foo>>::into(FoobuilderBuilder::build();
```

That is, the `FooBuilderBuilder::build()` method first construct the `FooBuilder` struct, and automatically convert it into `Foo` struct.

I think this is very helpful.
Thanks.

**Comment by idanarye** [comment]
Counter offer:

```rust
pub struct Foo {
    // ...
}

#[typed_builder::function(execute=build)]
pub fn make_foo(
    fields: That,
    you: Would,
    have: Put,
    inside: FooBuilder,
) -> Foo {
    // Code for making Foo
}
```

`make_foo()` would create the builder.

If we want it as a static method, we would have to do something like that:

```rust
pub struct Foo {
    // ...
}

#[typed_builder::methods]
impl Foo {
    #[builder(execute=build)]
    pub fn builder(
        fields: That,
        you: Would,
        have: Put,
        inside: FooBuilder,
    ) -> Foo {
        // Code for making Foo
    }
}
```

**Comment by idanarye** [comment]
Implementation-wise, non-static methods would be harder because they'd had to carry the `Foo` inside the builder...

**Comment by lebensterben** [comment]
Then let's just have the static method.

Thanks!

**Comment by SOF3** [comment]
I was rather thinking about a builder-style method call. Let's say we have this method:

```rust
pub fn foo(a: A, b: B, c: C = "c") {}
```

Right now we have to create a builder type for a struct `FooParams` containing all params, then users call the function like this:

```rust
foo(FooParams::builder().a(a).b(b).build())
```

I was trying to build on typed-builder to make this syntax easier by making `build` simply call `foo`, so the syntax can become like this:

```rust
foo().a(a).b(b).call()
```

where I can add a `call(self)` method which is simply `original_foo(self.build())`

So this issue can make constructing typed methods (especially in other codegen libraries) much easier.

**Comment by jquesada2016** [comment]
I came here to make this exact feature request. Very happy to know I am not the only one.

My current solution was to fork the repo and implement it for my specific use case. It's a simple workaround for now until this issue get's a solution.

**Comment by fMeow** [comment]
What's the progress of this feature request? Does anyonw working on this?

I have a workaournd to add custom logic when finalizing the builder, which is by calling `build()` method in normal cases.

- use cargo `expand` to get the generated build code like the following:
```rust
impl <__foo : Foo, __bar: Bar> MyTypeBuilder<(__foo, __bar)>{
    pub fn build() -> MyType{ 
    // ...
    }
}
```
- copy the `build()` function and rename it to another name like `finish` to avoid name conflict with the generated builder, and add code to the copied `finish` method.
```rust
impl <__foo : Foo, __bar: Bar> MyTypeBuilder<(__foo, __bar)>{
    pub fn finish() -> MyType{ 
    // copied from macro expanded code
   // add custom code, and 
    }
}
```

This way we are close to custom `build` method that additional code can be added when finalizing a builder with the `finish` method. 

However, this workaround could be troublesome that we now have two methods to finalize the builder, one called `finish` and another named `build`, which is generated by `TypedBuilder` proc-macro and should never be called.

I think we can simply add an option to disable generation of the final `build` method to make this workaround more robust, though I slightly against this idea since it reduces readbility.

**Comment by FlixCoder** [comment]
I would also very much like to change the output of the build function. I like the proposal of specifying a type, that implements `From/Into` for conversion to it. Should also just be small effort to implement.

**Comment by idanarye** [comment]
This ticket is already closed, so open a new one?

**Comment by FlixCoder** [comment]
It displays as open to me :o only the referenced issue is closed

**Comment by idanarye** [comment]
My bad. Did not scroll up...

**Comment by idanarye** [comment]
I'm okay with adding this new option, but a bit worried that the generated API will turn out weird - specifically that `Inner::builder().build()` will not return `Inner`. I guess that can be mitigated by makign `Inner::builder()` private?

I'm also thinking about allowing multiple build methods with:
```rust
#[builder(builder_method = [
    (name = build_inner), // return_type omitted, so it gets the default
    (return_type = Outer), // name omitted, so it defaults to `build`
])]
```

or something like that.

**Comment by FlixCoder** [comment]
Yes that sounds sensible to make the builder method private in that case.. Although it would not allow to build the inner type anymore either way, that is indeed a downside. Is it possible to make the return type `impl From<InnerBuilder>` and the user can decide themselves which type it shall be?

In the other hand it leads to users having to specify the type then

**Comment by FlixCoder** [comment]
I wonder if this can be closed now?

**Comment by idanarye** [comment]
Why not?
