### ISSUE TITLE
Set visibility for `builder` method and `-Builder` type

### ISSUE THREAD

**Issue by KSXGitHub** [idanarye/rust-typed-builder#74]
It is already possible to set visibility of `-Builder::build` to private, but it makes no sense to leave `builder` and `-Builder` in the public API.

## Suggestion

Add a `vis` attribute that set visibility for the `builder` method and the `-Builder` type. The `build` method may either be `pub` or the same as `vis`, it doesn't affect the public API.

**Example:**

```rust
#[derive(TypedBuilder)]
#[builder(vis = "pub(crate)")
struct MyType {
  foo: i32,
  bar: u32,
}

// MyType::builder and MyTypeBuilder both have visibility of pub(crate)
```

**Comment by idanarye** [comment]
I wonder if the `-Builder` type really should have the same visibility as the `builder` method? I can imagine a scenario where one would want to expose the builder type but not the method. Even though the current type do not really encourage it, people are still making the builder type part of their API, and it could make sense to hide the default builder method and expose other methods that return a semi-processed builder type.

**Comment by KSXGitHub** [comment]
@idanarye If people really want to set different visibilities for `-Builder` and `builder`, then we may have other options to override `vis`. But this is not what the issue is about. The concern of this issue is that there's currently no way to hide `builder` method and `-Builder` type from public API.

**Comment by idanarye** [comment]
Or I'll just add both:

```rust
#[derive(TypedBuilder)]
#[builder(
    builder_method(vis = ""),
    builder_type(vis = "pub(crate)"),
    build_method(vis = "pub"),
)]
struct MyType { ... }
```

If a visibility for `builder_method` is not provided though it'll be copied from the `builder_type` - otherwise the compiler will reject it (at least it will if the type is private - I've never checked for the other less-than-`pub` visibilities...)
