### ISSUE TITLE
Support no_std usage

### ISSUE THREAD

**Issue by jamesmunns** [idanarye/rust-typed-builder#9]
I haven't had a chance to check if this works on no_std, but I could see this crate being very useful in the embedded space!

**Comment by idanarye** [comment]
The main problem is that I use 3 things from `std` in the generated code - `Default`, `Into` and `PhantomData`. All these exist in `core`, but if I try to replace them with the ones from `core` I get a compilation error when I use it in crates that do use `std`, saying that I need to `extern crate core`...

**Comment by jamesmunns** [comment]
One nice trick is something like this:

```rust
// only assert no_std if configured by feature flag
#![cfg_attr(feature = "no_std", no_std)]

// pretend `std` is `core` on std builds
#[cfg(not(feature = "no_std"))]
use std as core;

use core::marker::PhantomData;
// ...
```

I can try and hack up a PR later today :)

**Comment by jamesmunns** [comment]
The use of this might vary between the 2015 and 2018 editions of rust, but I think that should get the point across.

**Comment by idanarye** [comment]
Yea, this works nice for regular library crates, but I need to generate code for the host crates - so I can't just set futures and inject `#![no_std]` for them...

**Comment by idanarye** [comment]
But if you want to give it a try, these are the offending lines:
* https://github.com/idanarye/rust-typed-builder/blob/master/src/struct_info.rs#L85
* https://github.com/idanarye/rust-typed-builder/blob/master/src/struct_info.rs#L95
* https://github.com/idanarye/rust-typed-builder/blob/master/src/struct_info.rs#L193
